custom:
  authorize-ignore-url: /**
  db-url: jdbc:mysql://localhost:3306/htfate?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
server:
  port: 52010
spring:
  application:
    name: user
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root_htfate
    password: root_htfate
    url: ${custom.db-url}
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  freemarker:
    cache: false
    expose-spring-macro-helpers: false
    suffix: .ftl
